feat(console): add a game console
GnuCodingStudio/GameZam002-still-steal pull request #18
Opened 2024-08-17 09:54 UTC by olivierperez

## Description

A game developer console to help debugging.

## Motivation and Context

It was hard to test the game without debugging tool.

## How has this been tested?

Manually, I typed on "²" on my AZERTY keyboard to make the game console appear.

## Screenshots (if appropriate):

[game-console.webm](https://github.com/user-attachments/assets/09a025bd-f21a-4926-aa32-099be131d1d8)

## Types of changes
- Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-08-26 11:31 UTC, AnthoMarquet commented
@olivierperez La touche "2" n'est pas dispo sur MacOS donc je ne peux pas tester. Il faudrait une touche "générique". Que penses tu de "@" ?

2024-08-26 11:35 UTC, AnthoMarquet requested changes
J'attends de pouvoir tester pour valider ;)

2024-08-26 11:35 UTC, AnthoMarquet commented on scenes/MainMenu.gd
> +			game_console.log_info("Cameras and Guards enabled")
disabled plutot qu'enabled

2024-08-26 11:35 UTC, AnthoMarquet commented on scenes/MainMenu.gd
> +			game_console.log_info("Cameras and Guards disabled")
enabled plutot que disabled

2024-08-26 12:06 UTC, olivierperez commented
J'ai corrigé les 2 logs + ajouté la touche "@" pour ouvrir la console

2024-08-28 07:20 UTC, AnthoMarquet commented
> J'ai corrigé les 2 logs + ajouté la touche "@" pour ouvrir la console
C'est tout bon pour ces deux ajustements

--

Vraiment sympa cette fonctionnalité. Elle pourra être réutilisée pour d'autres jeux :) 
Le point d'amélioration que je me note, c'est de pouvoir accéder à la console tout le temps pour éviter de devoir relancer le jeux si on veux changer un paramètre.

Code code / implémentation je te fais confiance :) Une petite explication en live sera bienvenue dès mon retour de congé.

Good job 💪 💯 

PS : Ajouter un konami code pour rendre "enable" les touches d'ouverture de à la console ;)

2024-08-28 07:20 UTC, AnthoMarquet approved these changes, later dismissed

2024-08-28 09:25 UTC, audreygentili approved these changes

2024-08-28 09:25 UTC, merged